development:
  clients:
    default:
      database: hook_dev
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: hook_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
